### PR TITLE
fix(seo): canonical url enforces html extension

### LINKED ISSUE #796: SEO: canonical URL always has .html extension
See `view-source:https://pages.adobe.com/illustrator/en/tl/thr-illustration-home/`

### PR DESCRIPTION
**Pull request by rofe**
Fix #796

### CODE REVIEW

**Comment by kptdobe** [comment]
I have read the test but I do not understand what is this supposed to do ;)

**Comment by rofe** [comment]
> I have read the test but I do not understand what is this supposed to do ;)

😂 it makes sure the canonical URL is built based on the `x-old-url` header instead of `request.url` (which for some reason at this point already comes fitted with an `html` extension).

**Comment by rofe** [comment]
@kptdobe I realized multiple tests were a bit overengineered, I simplified them all now.

**Review by trieloff — APPROVED** [review]

**Pull request merged**
