### PR TITLE
feat(blob): adjust to rootless image paths

### PR DESCRIPTION
**Pull request by rofe**
~~Removing `.` to in absolute path (works but ugly)~~
Resolve images starting with `./` relative to the path of the containing page.

### CODE REVIEW

**Review by tripodsan — APPROVED** [review]
i don't really understand the semantics here, but looks ok :-)

**Review by dominique-pfister — APPROVED** [review]

**Comment by rofe** [comment]
I just realized that this is actually wrong 😄 

`.` should be replaced with the path of the current request, not just removed, otherwise we can't benefit from the rootless paths at all.

**Comment by rofe** [comment]
OK, now it should work as follows:
1. An absolute meta image URL should stay as is
2. A relative meta image URL starting with `/` should be made absolute and equipped with optimization params:
   `/my/meta-image.jpg` -> `/my/meta-image.jpg?auto=webp&format=pjpg&optimize=medium&width=1200`
3. A relative meta image URL starting with `./` should be resolved relative to the page that contains it and optmized:
   `./media_123456.jpg` defined on `/my/page.html` -> `/my/media_123456.jpg?auto=webp&format=pjpg&optimize=medium&width=1200`

**Review by dominique-pfister — APPROVED** [review]

**Review by trieloff — APPROVED** [review]

**Review by tripodsan — APPROVED** [review]

**Pull request merged**
