### PR TITLE
feat(sidekick): publish to purge via fastly

### PR DESCRIPTION
**Pull request by rofe**
Use Fastly for purging instead of I/O Runtime directly.

### CODE REVIEW

**Review by tripodsan — CHANGES_REQUESTED** [review]
I don't like this. the idea of using helix-purge is, that it checks if everything is still ok before purging - as a little safe-guard against purging the outer CDN when somethings down.

what is the reason for changing this? also what is the `config.host`?

@trieloff WDYT?

**Comment by rofe** [comment]
The idea is to isolate from the underlying serverless platfrom and hide implementation details. I believe any safeguards should be built into `helix-purge` itself.

`config.host` is the optional "production host" config parameter (e.g. `blog.adobe.com`) for the sidekick.

cc @davidnuescheler

**Review by tripodsan — APPROVED** [review]
ah ok, I just saw the `HLXPURGE` that will forward it to helix-purge....

**Review by trieloff — APPROVED** [review]
Looks ok.

**Comment by rofe** [comment]
Working on adjusting `theblog-tests`

**Comment by rofe** [comment]
`theblog-tests` are now working with the latest sidekick version.

**Pull request merged**
