### PR TITLE
feat(sidekick): app and configurator

### LINKED ISSUE #545: Helix Sidekick
In reference to the CQ5 Sidekick, build a Helix equivalent which
- authors can toggle using a bookmarklet
- provides authors with contextual helpers
- loads custom extensions from the current Helix site

### PR DESCRIPTION
**Pull request by rofe**
Fix #545

### CODE REVIEW

**Review by trieloff — APPROVED** [review]

**Comment by kptdobe** [comment]
Same comment than for https://github.com/adobe/project-helix.io/pull/77#issuecomment-727810929: we should group everything together. Maintain 2 repos for the same feature make things complicated.

**Comment by rofe** [comment]
@trieloff do we have caching enabled for `www.hlx.page`?

**Comment by rofe** [comment]
I will move the sidekick app and tests here per discussion with @davidnuescheler.

**Comment by rofe** [comment]
@kptdobe the move from `project-helix.io` is complete now.

Th diff test failure is expected: I added a link to the sidekick configurator to the homepage.

**Review by kptdobe — APPROVED** [review]

**Pull request merged**
