### PR TITLE
feat(html): responsive images with <picture>

### LINKED ISSUE #657: Breaking March: <picture> default behaviour
it would be great to introduce responsive images in helix pages by default.

while there may be a broad range of configuration options, we can get to a place that is a significant improvement over the current behavior by changing the current img tag from eg:

```
            <img src="/hlx_dd76df9c9b121fec5f1b6bc39481247a1f756139.png">
```

to 

```
<picture>
            <source media="(max-width: 400px)" srcset="/hlx_dd76df9c9b121fec5f1b6bc39481247a1f756139.png?width=750&format=webply&optimize=medium" />
            <img loading="lazy" src="/hlx_dd76df9c9b121fec5f1b6bc39481247a1f756139.png?width=2000&format=webply&optimize=medium" alt=""/>
</picture>
```

with the first img set to `loading="eager"`

### PR DESCRIPTION
**Pull request by rofe**
Fix #657

This is a breaking DOM change, so `run_diff_tests` will fail.

@tripodsan do I need to merge this into a specific "breaking" branch eventually?

### CODE REVIEW

**Comment by tripodsan** [comment]
@rofe yes, we need to create a breaking branch and the rebase this onto it....

**Review by tripodsan — COMMENTED** [review]
I think this should be an extra pipeline step, or at least life in it's own file.

**Comment by rofe** [comment]
> this should be an extra pipeline step, or at least life in it's own file.

Agreed, but as it stands, there is no custom pipeline in Helix Pages yet, and I think we can still move this (and most of the other stuff in `html.pre.js` like metadata extraction, section wrapping etc) to pipeline steps later.

**Comment by trieloff** [comment]
If it works for pages, we can then move it into proper pipeline after a few weeks.

**Comment by rofe** [comment]
> create a breaking branch and the rebase this onto it
@tripodsan I created `breaking-march` and rebased this PR. how do i get rid of the failing `wip` GH workflow?

**Review by davidnuescheler — CHANGES_REQUESTED** [review]
i think this doesn't decorate the default `` with the expected image optimization suffixes, but maybe this happens somewhere else.

**Comment by rofe** [comment]
> i think this doesn't decorate the default `` with the expected image optimization suffixes, but maybe this happens somewhere else.

You're absolutely right, thanks! I missed that...

**Comment by tripodsan** [comment]
> If it works for pages, we can then move it into proper pipeline after a few weeks.

this doesn't align with our helix strategy. we don't want to extend the pipeline anymore, but rather steer towards a helix-pages service.

see:
- https://github.com/adobe/helix-pages/issues/639
- https://github.com/adobe/helix-home/discussions/174

**Comment by tripodsan** [comment]
> @tripodsan I created `breaking-march` and rebased this PR.

it should be named `breaking-202103`... 

>  how do i get rid of the failing `wip` GH workflow?

you remove the `breaking` label :-) but I think, we need to change the workflow to allow `breaking` and deny `block`.

**Comment by tripodsan** [comment]
@rofe the tests are also failing... I think we need to come to a state, where we can prepare the changes for the smoke tests (e.g. the breaking-march branch in theblog) and have the CI run them with the new changes enabled.

**Review by tripodsan — APPROVED** [review]

**Comment by rofe** [comment]
> you remove the breaking label :-)

When do i remove that? It will always stay breaking... ;)

**Comment by tripodsan** [comment]
> When do i remove that? It will always stay breaking... ;)

but it doesn't break the breaking branch :-)

maybe we need another label to really block merges. eg in other projects i used `block`

**Comment by rofe** [comment]
> @rofe the tests are also failing

I know, working on it. Interestingly the failing tests were unrelated to this, but #660 should take care of it.

**Comment by rofe** [comment]
> but it doesn't break the breaking branch :-)

That's what i thought. I would have expected the check to pass after I rebased the PR from `master` to `breaking-*` 😉

**Comment by rofe** [comment]
> the tests are also failing

Now all tests are green except the ones expected to fail due to the changed DOM (`run_diff_tests` and `theblog_tests`)

**Comment by tripodsan** [comment]
> > the tests are also failing
> 
> Now all tests are green except the ones expected to fail due to the changed DOM (`run_diff_tests` and `theblog_tests`)

ok, do you want to merge it into the breaking branch? then we can start to setup the test config

**Pull request merged**
