### PR TITLE
add gdrive-preview strain

### PR DESCRIPTION
**Pull request by dominique-pfister**
Adds a strain that will select a custom version of the `content-proxy` service if preflight is set to `gdrive-preview`

### CODE REVIEW

**Review by tripodsan — APPROVED** [review]

**Comment by tripodsan** [comment]
I don't think we need to merge this into master.... 

@trieloff we published this with `--only gdrive-preview`... I assume now it's in the edge dictionary of that strain. so it will remain even if we publish something new in master. right?

**Comment by trieloff** [comment]
Yes, but merging is still the clean thing to do.

**Review by rofe — APPROVED** [review]

**Comment by tripodsan** [comment]
@dominique-pfister can we close this? I don't think it's needed anymore.

**Comment by dominique-pfister** [comment]
> @dominique-pfister can we close this? I don't think it's needed anymore.

Right

**Comment by rofe** [comment]
@dominique-pfister @tripodsan fwiw, I think it would be great to either have a dedicated preview action, or a `fresh` param in the `content-proxy`, which would bust the relevant cache (basically what _Reload_ in the sidekick is doing today) before redirecting, so when an author clicks _Preview_ in the sidekick, they would immediately get the latest version of the page without having to click _Reload_ again.

**Pull request closed without merging**
