### PR TITLE
Sidekick patch

### LINKED ISSUE #579: Sidekick: Publish dependencies
When publishing a URL, there are often dependencies that need to be (re)published as well. The application should be able to define dependencies and store them as a global array. The Publish action would look for such an array and also publish all URLs in it.

### LINKED ISSUE #580: Sidekick: move to dedicated Helix namespace
The Helix Sidekick currently lives in the global variable `window.hlxSidekick` and expects the global `windo.hlxSidekickConfig` to be defined during initialization.

For better isolation, it should be moved to a proper namespace.

This is a breaking change, but can be mitigated by showing a `confirm()` dialog every time `window.hlxSidekick` or `window.hlxSidekickConfig` are detected, asking the user to go to the Sidekick generator to fetch the latest version.

### LINKED ISSUE #581: Sidekick: recycle preview/edit windows per document
The Sidekick is being a bit too careful not to clutter the user's browser tabs when opening preview and edit windows by recycling a single preview and edit window. This has proven impractical for authors, especially when working on several documents in parallel. 

Ideally, the Sidekick would still be mindful about the number of windows it opens, but only recycle a window if the source or target are the same.

### LINKED ISSUE #587: Sidekick: let users know if there is an updated version
... and give them an easy way to go install the new one and come back.

### LINKED ISSUE #593: Sidekick: Publish incorrectly requires a public host name
Publish should also work if you only have an inner CDN.

### PR DESCRIPTION
**Pull request by rofe**
Fix #580
Fix #581 
Fix #579 
Fix #587
Fix #593

### CODE REVIEW

**Comment by rofe** [comment]
Test Update URL:
https://sidekick-patch--helix-pages--adobe.hlx.page/tools/sidekick/?project=Blog&host=blog.adobe.com&giturl=https%3A%2F%2Fgithub.com%2Fadobe%2Ftheblog%2Ftree%2Fmaster&from=https%3A%2F%2Ftheblog--adobe.hlx.page%2Fen%2Fauthors%2Fjavier-angel.html

**Review by kptdobe — APPROVED** [review]

**Comment by rofe** [comment]
I think it's very impractical to also isolate the config in the `window.hlx` namespace, because users will have to check for namespace existence, and it will be thrown away after instantiation anyway. It can remain in `window.hlxSidekickConfig`.

**Comment by rofe** [comment]
On the other hand, the only user is the sidekick bookmarklet, so it's probably not worth refactoring everything again 😉

**Comment by rofe** [comment]
Test bookmarklet for Blog:
```
javascript:(() %3D> %7Bwindow.hlx%3Dwindow.hlx%7C%7C%7B%7D%3Bif(!window.hlx.sidekick)%7Bwindow.hlx.sidekickConfig%3D%7B"project":"Blog","host":"blog.adobe.com","owner":"adobe","repo":"theblog","ref":"master"%7D%3Bdocument.head.appendChild(document.createElement("script")).src%3D"https://sidekick-patch--helix-pages--adobe.hlx.page/tools/sidekick/app.js"%3B%7Delse%7Bwindow.hlx.sidekick.toggle()%3B%7D%7D)()%3B
```
When loading the new, namespaced Sidekick with a legacy bookmarklet, the following dialog will be shown each time the Sidekick is loaded:
image
OK will take the user to the Sidekick Configurator to grab a new one, Cancel will let them continue working on the same document.

**Review by kptdobe — APPROVED** [review]

**Pull request merged**
