### PR TITLE
feat(sitemap): remove sitemap.xml

### LINKED ISSUE #444: Disable (or remove) sitemap.xml
The auto-generated sitemap.xml (#118) has several unresolved issues, e.g.
- there is currently no way to add a `lastModified` to `loc`s
- if there are customized `externalPath`s they don't match the canonical URLs in the metadata
- the number of entries in the sitemap.xml are limited by the number of ESIs
- the number of entries per ESI are hardcoded to 100
- ~~the maximum file size is limited to 1MB by I/O Runtime~~ (overcome by using ESIs)
- the sitemap takes really long to generate on the inner CDN, and single ESI segments can fail, so you need to refresh several times to warm it all up before the outer CDN can pick it up and cache it

Currently no Helix Pages project we know about is using it, so we should disable or remove it until we have a working solution.

### PR DESCRIPTION
**Pull request by rofe**
Fix #444

### CODE REVIEW

**Review by kptdobe — APPROVED** [review]

**Review by tripodsan — APPROVED** [review]

**Comment by rofe** [comment]
Let's wait for https://github.com/adobe/helix-static/issues/380 to be fixed before merging this PR.

cc @trieloff

**Review by trieloff — CHANGES_REQUESTED** [review]
Please provide some documentation on creating your own sitemap instead.

**Comment by rofe** [comment]
> Please provide some documentation on creating your own sitemap instead.

https://github.com/adobe/helix-pages/pull/445#pullrequestreview-476561549

**Review by trieloff — APPROVED** [review]

**Comment by trieloff** [comment]
I'd prefer the docs to be in the readme, but won't block the PR.

**Comment by rofe** [comment]
> I'd prefer the docs to be in the readme, but won't block the PR.

Thanks ;) I added instructions to the docs folder, next to the feed.xml documentation.

**Pull request merged**
