### PR TITLE
Half-baked support for Atom Feeds

### PR DESCRIPTION
**Pull request by trieloff**
@dominique-pfister I'm looking to add support for Atom feeds, similar to our sitemap.xml support. I'm not clear how I can get the Algolia results sorted by date (so that the newest entries show up on top)

The idea is to create an `atom.xml` file in the `theblog` repository that has the root elements and includes the `cgi-bin/feed.xml` via ESI.

Also not sure why the smoke tests fail.

### CODE REVIEW

**Comment by dominique-pfister** [comment]
> I'm not clear how I can get the Algolia results sorted by date (so that the newest entries show up on top)

This happens automatically, because the index is preconfigured to be sorted by date.

> Also not sure why the smoke tests fail.

The [test failing](https://app.circleci.com/pipelines/github/adobe/helix-pages/1252/workflows/063e4bc0-7b87-4100-ab92-f303d277d4bd/jobs/3885/tests) checks that there's at least 1 url in the sitemap generated:
```
AssertionError [ERR_ASSERTION]: has 1+ url tags
    at Context.it (test/smoke/test.sitemap.output.js:37:14)
```
which fails, because Algolia Trial's has once again ended.

**Comment by trieloff** [comment]
Ready and documented.

**Comment by trieloff** [comment]
> Do we really want "half-baked"? 😉 

Yes. Just like headers, footers or sitemaps, site owners have needs to customize, so the half-baked approach allows them to completely bake it at home.

> what's missing to make it fully-baked?

https://github.com/adobe/helix-pages/blob/ea92461dd24b6ff50f1714c22312a7b2f130339e/docs/feed.md#how-to-add-an-atom-feed-to-your-helix-pages-website

**Pull request merged**
