### PR TITLE
chore(test): changes in static files are not tested

### LINKED ISSUE #513: Static files updates are not tested
This is a pretty critical issue.

While debugging for https://github.com/adobe/helix-pages/issues/493, I realised the test domains published by the CI (hlx-1...) do not render the branch version of the static files (head.html in that case).

To test (need to validate): 
- create a helix-pages branch
- change the `head.html`
- commit
- go to CircleCI and wait for the `init_smoketests` job of that branch to be finished
- expand the `Compute TEST_DOMAIN and TEST_SERVICE` step and note the test domain where the deployment has been made (hlx-X)
- request `https://www.hlx-X.page/head.html`

In order for the tests to be meaningful, this must be the one from the branch. But you still get the master one.
I assume the `hlx publish` we do in the CI must be configure to add a strain pointing to the branch as a content and static repo.

I can look into it but maybe @trieloff @tripodsan you have some ideas to share.

### PR DESCRIPTION
**Pull request by kptdobe**
Fix #513

2 majors changes:
- VCL: if `owner` and `repo` is present in the url but no `branch/ref`, default the `ref` to `master`. This was the case before but only because the `ref` defaults to helix-pages `branch`, i.e. `master`.
- Update the branch in `helix-config.yaml` prior to hlx publish so that the VCL code knows which is the current helix-pages `branch` to use and not only for the `code` part (`content` and `static`)

I put the PR in draft just to make sure it does not get merged before MAX.

### CODE REVIEW

**Review by trieloff — APPROVED** [review]
The hard coded `master` might become an issue with repos that use `main` as the default branch.

**Comment by kptdobe** [comment]
Yes. But that's not the only place (https://github.com/adobe/helix-publish/blob/master/layouts/fastly/helix.vcl#L269-L272) and it is a much more complicated story ;)

**Comment by kptdobe** [comment]
And I think with that change, we can switch to `main` for helix-pages, this should have no impact on customer site (not the case today since helix-pages branch determines the customer site branch to use...).
Once `main` will be the norm, we can toggle it in our VCL and ask customer that still uses `master` to put it in the url.
Actually, this would make it easy!

**Pull request merged**
