### PR TITLE
chore: improve diff tests

### PR DESCRIPTION
**Pull request by tripodsan**

### CODE REVIEW

**Review by kptdobe — APPROVED** [review]
Not sure what this improves apart from the "style"...

**Review by trieloff — APPROVED** [review]

**Comment by tripodsan** [comment]
> Not sure what this improves apart from the "style"...

you can run the tests now locally and they actually produce output.

**Comment by kptdobe** [comment]
Ah... adding the `--delay` locally was solving the pb too ;)

**Comment by tripodsan** [comment]
> Ah... adding the `--delay` locally was solving the pb too ;)

not really...there was no output. at least not for me.

**Pull request merged**
