### PR TITLE
feat(content): Support for google docs mounts

### LINKED ISSUE #67: Support for google docs mounts
For easy authoring it is cool to use a content provider like google docs for certain parts of a webpage. experimentally, this will be implement in the helix-pages scripts but could eventually be moved to helix proper.

## Approach

1. user shares a google drive folder with the helix bot
1. user puts a `fstab.json` in his helix-pages repository, containing a mount root and google docs folder id. eg:  
```
{
{
  "mountpoints": [
    {
      "root": "/mystuff",
      "type": "google",
      "id": "1I_FwT5qXkZTevAeZ9EqUqLaS0RbLFkI2"
    },
    {
      "root": "/private",
      "type": "google"
    }
  ]
}
```  
3. the pipeline will load the fstab and use the information to fetch the markdown from a google-docs provider (could be implemented as a runtime action in the future, using the docs/drive API directly)
4. if the mountpoint does not include a folder id, it is expected as a path segment. this allows for _private_ share links. eg: `https://www.notslides.io/private/1I_FwT5qXkZTevAeZ9EqUqLaS0RbLFkI2/welcome.html`

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #67

### CODE REVIEW

**Comment by tripodsan** [comment]
@kptdobe I tested it and it should be ok :-)

**Comment by kptdobe** [comment]
You merged but you did not consider my feedback: is the code under `google/helix-doc2markdown` our code ? If yes, I think it deserves some linting (use of `var`, random spacing, missing semi columns...).

**Comment by tripodsan** [comment]
> You merged but you did not consider my feedback

I didn't see any feedback :-)

**Comment by tripodsan** [comment]
> is the code under google/helix-doc2markdown our code 

yes, but it is google-script javascript (ecma script v5). I can try to adjust the eslint settings, so that we can catch formatting issue. also, it is edited in the google-script editor and only dumped here for reference...

**Pull request merged**
